---
language: java

sudo: false

dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
env:
  - NODE_VERSION=8

before_install:
  - nvm install $NODE_VERSION
  - npm install -g ember-cli
  - npm config set spin false
 
script:
  - (cd gcme-ember && npm install && ember test && cd -)
  - (cd gcme-tool && mvn test && cd -)
